#!/bin/bash

arg="$1"

function checkExit() {
    if [ "$?" = 0 ]; then
        exit 0
    else
        exit 1
    fi
}

if [ "$arg" = "0" ] && pass > /dev/null; then
    echo "$(pass show ssh_/ilab)"
    checkExit
elif [ "$arg" = "2" ]; then
     echo "$(pass show rutgers/cs_box)"
     checkExit
else
    exit 1
fi
